WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[rank1]:[W714 13:36:15.946061324 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank2]:[W714 13:36:15.957985910 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 2]  using GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank3]:[W714 13:36:15.958086098 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 3]  using GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank0]:[W714 13:36:15.958580496 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
wandb: Currently logged in as: saisoma239 (saisoma239-iowa-state-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.21.0
wandb: Run data is saved locally in /u/ssoma1/mahdi/Isomorphic-Pruning/wandb/run-20250714_133617-j4dfnhli
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run _work_hdd_bewo_mahdi_Isomorphic-Pruning_output_pruned_deit_4.2G_v2.pth
wandb: ‚≠êÔ∏è View project at https://wandb.ai/saisoma239-iowa-state-university/Pruning
wandb: üöÄ View run at https://wandb.ai/saisoma239-iowa-state-university/Pruning/runs/j4dfnhli
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:370: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler() if args.amp else None
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:370: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler() if args.amp else None
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:370: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler() if args.amp else None
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:370: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler() if args.amp else None
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location="cpu")
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location="cpu")
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location="cpu")
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location="cpu")
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:49: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=scaler is not None):
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:49: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=scaler is not None):
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:49: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=scaler is not None):
/u/ssoma1/mahdi/Isomorphic-Pruning/train.py:49: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=scaler is not None):
Traceback (most recent call last):
[rank1]: Traceback (most recent call last):
[rank1]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 641, in <module>
[rank1]:     main(args)
[rank1]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 459, in main
[rank1]:     train_one_epoch(model, teacher_model, criterion, optimizer, data_loader, device, epoch, args, model_ema, scaler)
[rank1]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 46, in train_one_epoch
[rank1]:     for i, (image, target) in enumerate(metric_logger.log_every(data_loader, args.print_freq, header)):
[rank1]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/pbench/utils.py", line 127, in log_every
[rank1]:     for obj in iterable:
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank1]:     data = self._next_data()
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1445, in _next_data
[rank1]:     return self._process_data(data)
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
[rank1]:     data.reraise()
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
[rank1]:     raise exception
[rank1]: ImportError: Caught ImportError in DataLoader worker process 3.
[rank1]: Original Traceback (most recent call last):
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
[rank1]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank1]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank1]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 245, in __getitem__
[rank1]:     sample = self.loader(path)
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 284, in default_loader
[rank1]:     return pil_loader(path)
[rank1]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 263, in pil_loader
[rank1]:     img = Image.open(f)
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3559, in open
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3547, in _open_core
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 870, in jpeg_factory
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/ImageFile.py", line 147, in __init__
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 394, in _open
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 504, in _read_dpi_from_exif
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 1540, in getexif
[rank1]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 4022, in load
[rank1]: ImportError: cannot import name 'TiffImagePlugin' from 'PIL' (/u/ssoma1/.local/lib/python3.9/site-packages/PIL/__init__.py)

[rank3]: Traceback (most recent call last):
[rank3]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 641, in <module>
[rank3]:     main(args)
[rank3]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 459, in main
[rank3]:     train_one_epoch(model, teacher_model, criterion, optimizer, data_loader, device, epoch, args, model_ema, scaler)
[rank3]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 46, in train_one_epoch
[rank3]:     for i, (image, target) in enumerate(metric_logger.log_every(data_loader, args.print_freq, header)):
[rank3]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/pbench/utils.py", line 127, in log_every
[rank3]:     for obj in iterable:
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank3]:     data = self._next_data()
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1445, in _next_data
[rank3]:     return self._process_data(data)
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
[rank3]:     data.reraise()
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
[rank3]:     raise exception
[rank3]: ImportError: Caught ImportError in DataLoader worker process 3.
[rank3]: Original Traceback (most recent call last):
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
[rank3]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank3]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank3]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 245, in __getitem__
[rank3]:     sample = self.loader(path)
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 284, in default_loader
[rank3]:     return pil_loader(path)
[rank3]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 263, in pil_loader
[rank3]:     img = Image.open(f)
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3559, in open
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3547, in _open_core
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 870, in jpeg_factory
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/ImageFile.py", line 147, in __init__
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 394, in _open
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 504, in _read_dpi_from_exif
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 1540, in getexif
[rank3]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 4022, in load
[rank3]: ImportError: cannot import name 'TiffImagePlugin' from 'PIL' (/u/ssoma1/.local/lib/python3.9/site-packages/PIL/__init__.py)

  File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 641, in <module>
    main(args)
  File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 459, in main
    train_one_epoch(model, teacher_model, criterion, optimizer, data_loader, device, epoch, args, model_ema, scaler)
  File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 46, in train_one_epoch
    for i, (image, target) in enumerate(metric_logger.log_every(data_loader, args.print_freq, header)):
  File "/u/ssoma1/mahdi/Isomorphic-Pruning/pbench/utils.py", line 127, in log_every
    for obj in iterable:
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1445, in _next_data
    return self._process_data(data)
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
ImportError: Caught ImportError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 245, in __getitem__
    sample = self.loader(path)
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 284, in default_loader
    return pil_loader(path)
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 263, in pil_loader
    img = Image.open(f)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3559, in open
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3547, in _open_core
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 870, in jpeg_factory
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/ImageFile.py", line 147, in __init__
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 394, in _open
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 504, in _read_dpi_from_exif
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 1540, in getexif
  File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 4022, in load
ImportError: cannot import name 'TiffImagePlugin' from 'PIL' (/u/ssoma1/.local/lib/python3.9/site-packages/PIL/__init__.py)

[rank0]: Traceback (most recent call last):
[rank0]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 641, in <module>
[rank0]:     main(args)
[rank0]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 459, in main
[rank0]:     train_one_epoch(model, teacher_model, criterion, optimizer, data_loader, device, epoch, args, model_ema, scaler)
[rank0]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/train.py", line 46, in train_one_epoch
[rank0]:     for i, (image, target) in enumerate(metric_logger.log_every(data_loader, args.print_freq, header)):
[rank0]:   File "/u/ssoma1/mahdi/Isomorphic-Pruning/pbench/utils.py", line 127, in log_every
[rank0]:     for obj in iterable:
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1445, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
[rank0]:     raise exception
[rank0]: ImportError: Caught ImportError in DataLoader worker process 3.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 245, in __getitem__
[rank0]:     sample = self.loader(path)
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 284, in default_loader
[rank0]:     return pil_loader(path)
[rank0]:   File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 263, in pil_loader
[rank0]:     img = Image.open(f)
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3559, in open
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 3547, in _open_core
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 870, in jpeg_factory
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/ImageFile.py", line 147, in __init__
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 394, in _open
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 504, in _read_dpi_from_exif
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 1540, in getexif
[rank0]:   File "/u/ssoma1/.local/lib/python3.9/site-packages/PIL/Image.py", line 4022, in load
[rank0]: ImportError: cannot import name 'TiffImagePlugin' from 'PIL' (/u/ssoma1/.local/lib/python3.9/site-packages/PIL/__init__.py)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/u/ssoma1/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
  File "/u/ssoma1/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
BrokenPipeError: [Errno 32] Broken pipe
W0715 14:14:59.211703 1566862 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1567264 closing signal SIGTERM
W0715 14:14:59.213650 1566862 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1567265 closing signal SIGTERM
W0715 14:14:59.213895 1566862 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1567266 closing signal SIGTERM
E0715 14:15:02.695373 1566862 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -7) local_rank: 0 (pid: 1567263) of binary: /u/ssoma1/.conda/envs/iso_env/bin/python
Traceback (most recent call last):
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/u/ssoma1/.conda/envs/iso_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-15_14:14:59
  host      : gpua014.delta.ncsa.illinois.edu
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 1567263)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 1567263
=======================================================
Fatal Python error: Bus error

Current thread 0x00007fbb2c930600 (most recent call first):
<no Python frame>
/var/spool/slurmd/job11024310/slurm_script: line 49: 1566862 Bus error               $CONDA_PYTHON -m torch.distributed.run --nproc_per_node=4 --master_port=23355 train.py --model "/work/hdd/bewo/mahdi/Isomorphic-Pruning/output/pruned/deit_4.2G_v2.pth" --teacher-model regnety_160.deit_in1k --epochs 300 --batch-size 256 --opt adamw --lr 0.0005 --wd 0.05 --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 0 --lr-warmup-decay 0.033 --amp --label-smoothing 0.1 --mixup-alpha 0.8 --auto-augment ra --ra-sampler --random-erase 0.25 --cutmix-alpha 1.0 --data-path "/work/hdd/bewo/mahdi/imagenet" --output-dir "/work/hdd/bewo/mahdi/Isomorphic-Pruning/output/finetuned/deit_4.2G_v2" --interpolation bicubic --resume "/work/hdd/bewo/mahdi/Isomorphic-Pruning/output/finetuned/deit_4.2G_v2/checkpoint.pth"
